Add validator command
lukso-network/tools-lukso-cli-deprecated pull request #62
Opened 2022-07-18 08:47 UTC by andocodes

2022-07-18 12:26 UTC, NandoTheessen requested changes

2022-07-18 12:26 UTC, NandoTheessen commented on src/network/add_validators.go
> +	fmt.Println("You are currently have:")
Small typo here :)

2022-07-18 12:26 UTC, NandoTheessen commented on src/network/add_validators.go
> +	password := "asdasd"
I imagine this need to be changed

2022-07-18 12:26 UTC, NandoTheessen commented on src/network/add_validators.go
> +	err = av.configs.ValidatorCredentials.GenerateDepositDataWithRange(av.configs.DepositDetails, oldCredentials.ValidatorRange())
Is the ValidatorRange on oldCredentials updated?

2022-07-19 12:53 UTC, andocodes commented on src/network/add_validators.go
> +	err = av.configs.ValidatorCredentials.GenerateDepositDataWithRange(av.configs.DepositDetails, oldCredentials.ValidatorRange())
Updated a few lines above! - `oldCredentials.ValidatorIndexTo = av.newNumberOfValidators()`

2022-07-19 13:00 UTC, andocodes commented on src/network/add_validators.go
> +	password := "asdasd"
Good catch!

2022-07-19 13:03 UTC, NandoTheessen approved these changes

2022-07-19 13:07 UTC, merged